services:
  Apps.Core.Controllers.RegisterPostController:
    class: src/apps/Core/controllers/http/User/RegisterPostController
    arguments: ["@Shared.CommandBus"]

  Apps.Core.Controllers.UserDeleteController:
    class: src/apps/Core/controllers/http/User/UserDeleteController
    arguments: ["@Shared.CommandBus"]

  Apps.Core.Controllers.UserRolePatchController:
    class: src/apps/Core/controllers/http/User/UserRolePatchController
    arguments: ["@Shared.CommandBus"]

  Apps.Core.Controllers.MyselfGetController:
    class: src/apps/Core/controllers/http/User/MyselfGetController
    arguments: ["@Shared.QueryBus", "@Shared.TokenDecoder"]

  Apps.Core.Controllers.UsersGetController:
    class: src/apps/Core/controllers/http/User/UsersGetController
    arguments: ["@Shared.QueryBus"]

  Apps.Core.Controllers.UserGetController:
    class: src/apps/Core/controllers/http/User/UserGetController
    arguments: ["@Shared.QueryBus"]
  
  Apps.Core.Controllers.SocketHealthController:
    class: src/apps/Core/controllers/socket/healthController
    arguments: []
  
  Apps.Core.Controllers.UserPasswordPatchController:
    class: src/apps/Core/controllers/http/User/UserPasswordPatchController
    arguments: ["@Shared.CommandBus"]