services:
  Apps.Core.Middlewares.AuthMiddleware:
    class: src/apps/Core/middleware/AuthMiddleware
    arguments: ["@Shared.TokenDecoder"]

  Apps.Core.Controllers.UserPostController:
    class: src/apps/Core/controllers/http/User/UserPostController
    arguments: ["@Shared.CommandBus"]

  Apps.Core.Controllers.UsersGetController:
    class: src/apps/Core/controllers/http/User/UsersGetController
    arguments: ["@Shared.QueryBus"]

  Apps.Core.Controllers.UserGetByIdController:
    class: src/apps/Core/controllers/http/User/UserGetByIdController
    arguments: ["@Shared.QueryBus"]

  Apps.Core.Controllers.UserDeletePatchController:
    class: src/apps/Core/controllers/http/User/UserDeletePatchController
    arguments: ["@Shared.CommandBus"]

  Apps.Core.Controllers.UserPatchNameController:
    class: src/apps/Core/controllers/http/User/UserPatchNameController
    arguments: ["@Shared.CommandBus"]

  Apps.Core.Controllers.UserPatchPasswordController:
    class: src/apps/Core/controllers/http/User/UserPatchPasswordController
    arguments: ["@Shared.CommandBus"]

  Apps.Core.Controllers.UserPatchPhoneController:
    class: src/apps/Core/controllers/http/User/UserPatchPhoneController
    arguments: ["@Shared.CommandBus"]

  Apps.Core.Controllers.SocketHealthController:
    class: src/apps/Core/controllers/socket/healthController
    arguments: []

  Apps.Core.Controllers.UserLoginPostController:
    class: src/apps/Core/controllers/http/User/UserLoginPostController
    arguments: ["@Shared.QueryBus"]
